# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/chrispy/workspace/cod_lab4/cod_lab4.cache/wt [current_project]
set_property parent.project_path /home/chrispy/workspace/cod_lab4/cod_lab4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo /home/chrispy/workspace/cod_lab4/cod_lab4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/full_adder.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/add_sub_16.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/adder_subtractor_16.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/and_16.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/not_16.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/or_16.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/xor_16.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/sll_16.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/srl_16.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/sra_16.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/Mux8to1_16.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/zero_check_16.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/ALU_16.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/mux2to1_3.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/registerfile_16by8.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/mux2to1_16.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/imports/cod_lab4/mem_16.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/imports/cod_lab4/sign_extentor.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/data_path.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/data_path_wpc.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/mux2to1_4.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/control_unit.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/new/processor_toplevel.vhd
}
read_vhdl -library knappe_lib {
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/imports/knappe_code/instruction_mem_16.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/imports/knappe_code/PC_adder.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/imports/knappe_code/PC_mux.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/imports/knappe_code/PC.vhd
  /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/sources_1/imports/knappe_code/PC_topleve.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/constrs_1/imports/digilent-xdc-master/Basys-3-Master.xdc
set_property used_in_implementation false [get_files /home/chrispy/workspace/cod_lab4/cod_lab4.srcs/constrs_1/imports/digilent-xdc-master/Basys-3-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top processor_toplevel -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef processor_toplevel.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file processor_toplevel_utilization_synth.rpt -pb processor_toplevel_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
