#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Nov 19 18:01:56 EST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim processor_toplevel_testbench_behav -key {Behavioral:sim_1:Functional:processor_toplevel_testbench} -tclbatch processor_toplevel_testbench.tcl -view /home/chrispy/workspace/cod_lab4/datapath_wpc_tb_behav.wcfg -log simulate.log"
xsim processor_toplevel_testbench_behav -key {Behavioral:sim_1:Functional:processor_toplevel_testbench} -tclbatch processor_toplevel_testbench.tcl -view /home/chrispy/workspace/cod_lab4/datapath_wpc_tb_behav.wcfg -log simulate.log

